# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/Code/oss/aggregate/python.app-feedstock/recipe, last modified Thu Feb  3 18:23:27 2022
# ------------------------------------------------

package:
  name: python.app
  version: '3'
build:
  number: '0'
  string: py310h1a28f6b_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 h5a0b063_4
  host:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2021.10.26 hca03da5_2
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.4.2 hc377ac9_2
    - ncurses 6.3 h1a28f6b_2
    - openssl 1.1.1m h1a28f6b_0
    - python 3.10.0 hbdb9e5c_3
    - readline 8.1.2 h1a28f6b_1
    - sqlite 3.37.0 h1058600_0
    - tk 8.6.11 hb8d0fd4_0
    - tzdata 2021e hda174b7_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
  run:
    - python >=3.10,<3.11.0a0
test:
  commands:
    - python.app -V
    - pythonw -V
  files:
    - t.py
about:
  home: https://www.python.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Proxy on macOS letting Python libraries hook into the GUI event loop
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ChrisBarker-NOAA
    - cpbotha
    - hoechenberger
