# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/Code/oss/aggregate/pysocks-feedstock/recipe, last modified Thu Feb  3 18:23:19 2022
# ------------------------------------------------

package:
  name: pysocks
  version: 1.7.1
source:
  sha256: 3f8804571ebe159c380ac6de37643bb4685970655d3bba243530d6558b799aa0
  url: https://pypi.io/packages/source/P/PySocks/PySocks-1.7.1.tar.gz
build:
  number: '0'
  script: /Users/ktietz/ci_310/pysocks_1643961536721/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv
  string: py310hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2021.10.26 hca03da5_2
    - certifi 2021.10.8 py310hca03da5_2
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.4.2 hc377ac9_2
    - ncurses 6.3 h1a28f6b_2
    - openssl 1.1.1m h1a28f6b_0
    - pip 21.2.4 py310hca03da5_0
    - python 3.10.0 hbdb9e5c_3
    - readline 8.1.2 h1a28f6b_1
    - setuptools 58.0.4 py310hca03da5_0
    - sqlite 3.37.0 h1058600_0
    - tk 8.6.11 hb8d0fd4_0
    - tzdata 2021e hda174b7_0
    - wheel 0.32.3 py310hca03da5_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
  run:
    - python >=3.10,<3.11.0a0
test:
  imports:
    - socks
about:
  dev_url: https://github.com/Anorov/PySocks
  doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
  home: https://github.com/Anorov/PySocks
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python SOCKS client module. See https://github.com/Anorov/PySocks for
    more information.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
