# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: python
  version: 3.10.9
source:
  - patches:
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0003-Support-cross-compiling-byte-code.patch
      - patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
      - patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0006-Win32-Do-not-download-externals.patch
      - patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0010-Unvendor-openssl.patch
      - patches/0011-Unvendor-sqlite3.patch
      - patches/0012-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0014-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
      - patches/0015-Doing-d1trimfile.patch
      - patches/0016-cross-compile-darwin.patch
      - patches/0017-Fix-TZPATH-on-windows.patch
      - patches/0018-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0019-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
      - patches/0020-Unvendor-bzip2.patch
      - patches/0021-Unvendor-libffi.patch
      - patches/0022-Unvendor-tcltk.patch
      - patches/0023-unvendor-xz.patch
      - patches/0024-unvendor-zlib.patch
      - patches/0025-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
    sha256: 5ae03e308260164baba39921fdb4dbf8e6d03d8235a939d4582b33f0b5e46a83
    url: https://www.python.org/ftp/python/3.10.9/Python-3.10.9.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - clangxx_osx-arm64 14.*
  no_link: null
  number: 0
  script_env:
    - CONDA_FORGE=no
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  string: hc0d8a6c_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gettext 0.21.0 h826f4ad_0
    - icu 68.1 hc377ac9_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libllvm14 14.0.6 h7ec7a93_1
    - libtool 2.4.6 h313beb8_1009
    - libxml2 2.9.14 h8c5e841_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - llvm-tools 14.0.6 h7ec7a93_1
    - make 4.3 h620ffc9_1
    - pkg-config 0.29.2 h1a28f6b_0
    - sed 4.8 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.2.8 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  host:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2022.10.11 hca03da5_0
    - libffi 3.4.2 hca03da5_6
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - readline 8.1.2 h1a28f6b_1
    - sqlite 3.40.1 h7a7dc30_0
    - tk 8.6.12 hb8d0fd4_0
    - xz 5.2.8 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libffi >=3.4,<3.5
    - libffi >=3.4,<4.0a0
    - ncurses >=6.3,<7.0a0
    - openssl >=1.1.1s,<1.1.2a
    - readline >=8.1.2,<9.0a0
    - sqlite >=3.40.1,<4.0a0
    - tk >=8.6.12,<8.7.0a0
    - tzdata
    - xz >=5.2.8,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv/bin/python -c "import ctypes"
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.10.9
    - popd
    - popd
    - python run_test.py
    - test ! -f default.profraw
    - test -d "$PREFIX/lib/python3.1/site-packages"
    - python3.1 --version
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils/*
    - tests/prefix-replacement/*
  requires:
    - clang_osx-arm64 14.*
    - clangxx_osx-arm64 14.*
    - cmake
    - make
    - ninja
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://devguide.python.org/
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  license_url: https://docs.python.org/3/license.html
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  flow_run_id: 5e425799-8547-47fa-bb12-d0c738b93b47
  recipe-maintainers:
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/python-feedstock.git
  sha: 17c1c8341f0c2bf61e580faf420664ea901fdb13
